INSERT INTO book (author, booktitle, image, genre) VALUES ('Ашли Ванс','Илън Мъск','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Брайън Джоунс','Джордж Лукас','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Лабиринт','Мей Мъск','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Шонън Лий','Бъди вода, приятелю','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Петер Молин & Петер Нистрьом','Списъкър','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Фил Кинг','Изкуството на победата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Питър Тийл','От Нула До Едно','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Менсън','Тънкото изкуство да не ти пука','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Остин Клиън','Покажи своето творчество','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Остин Клиън','Кради като артист','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Робин Шарма','Вдъхновение за всеки ден','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Стив Чандлър','100 начина да мотивираш себе си','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Кристина Мороци, Масимо Темпорели','Леонардо - Първият Дизайнер','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Глибри','Изкуството да живеем просто','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Петра Хартлиб','Моята Прекрасна Кницарница','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Маккъргоу, Хелън Бейли','Гостоприемно Лидерство','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Наполеон Хил','Да прецакаш дявола','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Мия Шеридан','Оцеляване','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','','','');