INSERT INTO book (author, booktitle, image, genre) VALUES ('Маршал Голдсмит','С каквото си успял, с него няма да преуспееш','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дейл Карнеги','Как да печелим приятели и да влияем на другите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Питър Сейдж','Успехология. Нагласи, ценности и визия на щастливия човек','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Доналд Тръмп','Пътят към успеха: Най добрият бизнес съвет които съм получавал','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дан Хийт, Чип Хийт','Промяната: Как да я постигнем когато е трудна','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джордан Б. Питърсън','Отвъд реда. Още 12 правила за живота','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Хенри Форд Моят живот и работа. Автобиография','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Бизнес отвъд ограниченията. Опитът на един предприемач','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Майната му! Да го направим! Уроците на живота ми','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Like a Virgin: Бизнес тайни, които не се преподават в училище','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Брайън Трейси','Без Извинения! Силата на Самодисциплината','','');

INSERT INTO book (author, booktitle, image, genre) VALUES ('','Голямата Стагнация','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Краят на посредствеността','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Ракетаджии','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Прекосяване на бездната','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Дифузия на иновациите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Лендмарк Букс','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Швейцарското семейство Робинзон','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','100 златни правила за успех в бизнеса и любовта','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Капитана отиде на обяд и моряците завзеха кораба','','')
INSERT INTO book (author, booktitle, image, genre) VALUES ('Малкълм Гладуел','Проблясък. Силата на мигновените решения','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Duped: Truth-Default Theory and the Social Science of Lying and Deception','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Измамени: теорията за презумпцията за истинност и социална наука за лъжата и измамата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джина Пери','Зад електрошоковата машина','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Чарлс Ремсбърг','Тактика на криминалния патрул','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Мисли като милионер и ще станеш милионер','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','От варвари към бюрократи. Стратегии на корпоративния жизнен цикъл','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('У. Чан Ким и Рене Мобьорно','Стратегия Син океан: Как да създаваме неоспоримо пазарно пространство и да обезсилваме конкуренцията','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Спасителят в ръжта','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Символите на тайните секти','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изкуството на илюминатите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изчезналият език на идеограмите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джон Кенеди Тул','Сговор на глупци','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Боен клуб','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Сбогом на оръжията','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Бъд Шулбърг','Кое кара Сами да тича','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Символите на изгубената свещена женственост','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Пътят','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Как да печелим приятели и да влияем на хората','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Магията на(да) мащабното мислене','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Силата на положителното мислене','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('У. Х. Мъри','Шотландската хималайска експедиция','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','The Courage to Succeed','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Човек на почит','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Специалист от Сицилия','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('null','Как да манипулираме хората','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Кажи на живота "ДА"','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Арън Т. Бек, Артър Фрийман','Когнитивна терапия на личностните разстройства','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Чужденецът','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изгнанието и царството','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Пропадане','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Чумата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Митър за Сизиф','','');


INSERT INTO book (author, booktitle, image, genre) VALUES ('','How to Think','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Eric Ries','The Lean Startup','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Jason Fried and David Heinemeier','ReWork','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Jim Collins','Good to Great','','');