INSERT INTO book (author, booktitle, image, genre) VALUES ('Ашли Ванс','Илън Мъск','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Лабиринт','Мей Мъск','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Брайън Джоунс','Джордж Лукас','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Шонън Лий','Бъди Вода, Приятелю','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Петер Молин & Петер Нистрьом','Списъкър','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Фил Кинг','Изкуството на Победата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Питър Тийл','От Нула До Едно','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Менсън','Тънкото изкуство да не ти пука','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Остин Клиън','Покажи Своето Творчество','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Остин Клиън','Продължавай Напред','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Остин Клиън','Кради Като Артист','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Робин Шарма','Вдъхновение За Всеки Ден','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Стив Чандлър','100 Начина Да Мотивираш Себе Си','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Кристина Мороци, Масимо Темпорели','Леонардо - Първият Дизайнер','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Глибри','Изкуството да живеем просто','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Петра Хартлиб','Моята Прекрасна Кницарница','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Маккъргоу, Хелън Бейли','Гостоприемно Лидерство','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Наполеон Хил','Да Прецакаш Дявола','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Мия Шеридан','Оцеляване','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Райън Холидей','Изкуството да бъдеш Спокоен','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джериес Авад','Скритият Дар','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('У. Клемънт Стоун','Вярвай и Успявай','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Саймън Синек','Започни със Защо','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Наполеон Хил','Мисли и Забогатявай','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Д-Р Габор Мате','Разпилян Ум','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Гнездото','Истинктът на Волята','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Шеста Кохорта','Как да общуваме с непознати','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Лиандър Кейни','Тим Кук','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дейл Карнеги','Изкуството да говорим пред другите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Карол Марш','Загадката за Биг Бен','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('АМГ','Ричърд Брансън Как открих найвността си','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Робърт Т. Кийосаки','Богат Татко Бтден Татко','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Рубен Гонзалес','Как да стигнем там, където искате да сте','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Любослав Любенов','Сексуално Привличане','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Робърт Грийн','Изкуството да съблазняваш','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Маршал Голдсмит','С каквото си успял, с него няма да преуспееш','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Райън Холидей','Твоето Его е Врагът','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дейл Карнеги','Как да печелим приятели и да влияем на другите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джон Кехол','Подсъзнанието може всичко','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Питър Сейдж','Успехология. Нагласи, ценности и визия на щастливия човек','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Гай Кавазаки','Изкуството да очароваш','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джим Куин','Безграничният потенциал','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Яна Йотова','Изкуството да живееш бавно','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Менсън','Тънкото изкуство на съблазняването','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Доналд Тръмп','Пътят към успеха: Най добрият бизнес съвет които съм получавал','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дан Хийт, Чип Хийт','Промяната: Как да я постигнем когато е трудна','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джордан Б. Питърсън','Отвъд реда. Още 12 правила за живота','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Грег Маккюън','С лекота','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Хенри Форд Моят живот и работа. Автобиография','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джо Диспенза','Разчупете навика да бъдете себе си','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ичиро Кишими, Фумитаке Кога','Смелостта да не те харесват','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Как изгубих найвността си','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Бизнес отвъд ограниченията. Опитът на един предприемач','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Бизнесът на бъдещето','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Методът Virgin','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Майната му! Да го направим! Уроците на живота ми','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Ричърд Брансън','Like a Virgin: Бизнес тайни, които не се преподават в училище','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Да се научим да умираме','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Аз съм добре и ти си добре','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Невидимия живот на Ади Лару','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Гранд Кардон','Правилото 10Х','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Стратегията син океан','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Тайна за милиард долара','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Хакнатия Човек','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Да се чувстваш страхотно','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Голямата Стагнация','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Краят на посредствеността','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Следвай Сърцето Си','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Безкрайна игра','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Лидерите винаги обядват последни','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Земята е Плоска','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Ракетаджии','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Прекосяване на бездната','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Дифузия на иновациите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Повратна Точка','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','От дъното към върха','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Голият мозък','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изкуствен Интелект','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Лендмарк Букс','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Швейцарското семейство Робинзон','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Островът на Съкровищата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Отвлечен','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Бейлс и Тед Орланд','Изкуство и Страх','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Тим Крайдър','Не учим нищо','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Твойте 5 хода напред','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','100 златни правила за успех в бизнеса и любовта','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Доктор Сън','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Сияние','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','На три стъпки от златото','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Нещата които носега','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Големите надежди','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Старо Училище','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Капитана отиде на обяд и моряците завзеха кораба','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Успехът е избор','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Проблясък. Силата на мигновените решения','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Duped: Truth-Default Theory and the Social Science of Lying and Deception','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Измамени: теорията за презумпцията за истинност и социална наука за лъжата и измамата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джина Пери','Зад електрошоковата машина','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Чарлс Ремсбърг','Тактика на криминалния патрул','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Мисли като милионер и ще станеш милионер','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Брайън Трейси','Стоте абсолютни закона на бизнес успеха','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Брайън Трейси','Силата на твоя чар','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Виктор Хансен','Пилешка супа за душата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Виктор Хансен','Да разбиеш кода на Милионера','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Марк Виктор Хансен','Милионер за една минута','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','От варвари към бюрократи. Стратегии на корпоративния жизнен цикъл','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('У. Чан Ким и Рене Мобьорно','Стратегия Син океан: Как да създаваме неоспоримо пазарно пространство и да обезсилваме конкуренцията','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','How to Think','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джордан Б. Питърсън','Отвъд Реда: Още 12 правила за живота','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Райън Холидей','Изкуството да Живееш','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Брайън Трейси','Без Извинения! Силата на Самодисциплината','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Емили Хенри','Чета те като книга','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Eric Ries','The Lean Startup','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Jason Fried and David Heinemeier','ReWork','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Jim Collins','Good to Great','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Спасителят в ръжта','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джон Фанти','Питай прахта','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джон Фанти','Квартетът на Бандини','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Уокър Пърси','Киноманът','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дан Браун','Шестото Клеймо','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Символите на тайните секти','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изкуството на илюминатите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изчезналият език на идеограмите','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Мегън Марч','Късметът на дявола','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Джон Кенеди Тул','Сговор на глупци','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Боен клуб','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Сбогом на оръжията','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Бъд Шулбърг','Кое кара Сами да тича','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Символите на изгубената свещена женственост','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Пътят','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Как да печелим приятели и да влияем на хората','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Магията на(да) мащабното мислене','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Силата на положителното мислене','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Дан Браун','Произход','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('У. Х. Мъри','Шотландската хималайска експедиция','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','The Courage to Succeed','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Човек на почит','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Специалист от Сицилия','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('null','Как да манипулираме хората','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Произходът','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Кажи на живота "ДА"','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('Арън Т. Бек, Артър Фрийман','Когнитивна терапия на личностните разстройства','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Чужденецът','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Изгнанието и царството','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Пропадане','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Чумата','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','Митър за Сизиф','','');
INSERT INTO book (author, booktitle, image, genre) VALUES ('','','','');