export const TABLE_NAMES = {
    AUTHOR_FILE: 'authorFile',
    AUTHOR: 'author',
    FILE: 'file',
    MESSAGE_STATUS: 'messageStatus',
    MESSAGE: 'message',
    PRODUCT_AUTHOR: 'productAuthor',
    PRODUCT_FILE: 'productFile',
    PRODUCT_STATUS: 'productStatus',
    PRODUCT_STATUS_HISTORY: 'productStatusHistory',
    PRODUCT_RATING: 'productRating',
    PRODUCT: 'product',
    SESSION: 'session',
    STATE: 'state',
    USER: 'user',
    PROFILE: 'profile',
} as const;
