name: Build Number Update

on:
  push:
    branches:
    - develop
  pull_request:
    types: [closed]

jobs:
  update_version:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Update version and build number
      run: chmod +x bash/update_build_number.sh && bash/update_build_number.sh

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json
        git commit -m "Build Number Update"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PIPELINE_TOKEN }}
        branch: develop
